Symfony/SUPERBLOG-master/src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BlogRepository::class)]
class Blog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\ManyToOne(inversedBy: 'blogs')]
    private ?User $user = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $ModifyAt = null;

    #[ORM\OneToMany(mappedBy: 'blog', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_alt = null;

    public function __construct(){
        $this->createAt = new \DateTimeImmutable('now');
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeImmutable $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function getModifyAt(): ?\DateTimeInterface
    {
        return $this->ModifyAt;
    }

    public function setModifyAt(?\DateTimeInterface $ModifyAt): self
    {
        $this->ModifyAt = $ModifyAt;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setBlog($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getBlog() === $this) {
                $comment->setBlog(null);
            }
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getImageAlt(): ?string
    {
        return $this->image_alt;
    }

    public function setImageAlt(?string $image_alt): self
    {
        $this->image_alt = $image_alt;

        return $this;
    }
}

Symfony/SUPERBLOG-master/src/Form/BlogType.php
<?php

namespace App\Form;

use App\Entity\Blog;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\Extension\Core\Type\FileType;



class BlogType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('image', FileType::class, [ # but this way we shall have to reload an image every time we edit a blog
                'required' => false,
                'label' =>"Image de l'article",
                'data_class' => null,
            ])
            ->add('image_alt')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Blog::class,
        ]);
    }
}

Symfony/SUPERBLOG-master/src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use App\Form\BlogType;
use App\Repository\BlogRepository;
use App\Repository\CommentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\FileUpLoader;

#[Route('/blog')]
class BlogController extends AbstractController
{
    #[Route('/', name: 'app_blog_index', methods: ['GET'])]
    public function index(BlogRepository $blogRepository): Response
    {
        return $this->render('blog/index.html.twig', [
            'blogs' => $blogRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_blog_new', methods: ['GET', 'POST'])]
    public function new(Request $request, BlogRepository $blogRepository): Response
    {
        $blog = new Blog();
        $form = $this->createForm(BlogType::class, $blog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $blog->setUser($this->getUser());
            $blogRepository->save($blog, true);

            return $this->redirectToRoute('app_blog_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('blog/new.html.twig', [
            'blog' => $blog,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_blog_show', methods: ['GET'])]
    public function show(Blog $blog, CommentRepository $commentRepository): Response
    {
        $comments = $commentRepository->findByBlog($blog);

        return $this->render('blog/show.html.twig', [
            'blog' => $blog,
            'comments' => $comments
        ]);
    }

    #[Route('/{id}/edit', name: 'app_blog_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Blog $blog, BlogRepository $blogRepository, FileUpLoader $fu): Response
    {
        $form = $this->createForm(BlogType::class, $blog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $uploadFiles = $form->get('image')->getData();
            $imageFilename = $fu->upload($uploadFiles); # va récupérer le return de fileUpload
            $blog->setImage($imageFilename);
            $blog->setModifyAt(new \DateTime('now'));
            $blogRepository->save($blog, true);

            return $this->redirectToRoute('app_blog_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('blog/edit.html.twig', [
            'blog' => $blog,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_blog_delete', methods: ['POST'])]
    public function delete(Request $request, Blog $blog, BlogRepository $blogRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$blog->getId(), $request->request->get('_token'))) {
            $blogRepository->remove($blog, true);
        }

        return $this->redirectToRoute('app_blog_index', [], Response::HTTP_SEE_OTHER);
    }
}

Symfony/SUPERBLOG-master/templates/blog/_delete_form.html.twig
<form method="post" action="{{ path('app_blog_delete', {'id': blog.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ blog.id) }}">
    <button class="btn">Delete</button>
</form>

Symfony/SUPERBLOG-master/templates/blog/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Symfony/SUPERBLOG-master/templates/blog/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Blog{% endblock %}

{% block body %}
    <h1>Edit Blog</h1>

    {{ include('blog/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_blog_index') }}">back to list</a>

    {{ include('blog/_delete_form.html.twig') }}
{% endblock %}

Symfony/SUPERBLOG-master/templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blog index{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">

                <nav class="navbar navbar-light bg-light justify-content-between">
                    <a class="navbar-brand">Liste des Articles</a>
                    <form class="form-inline">
                        <div class="input-group">
                            <input class="form-control" type="search" placeholder="Rechercher dans les titres" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Rechercher dans les titres</button>
                        </div>
                    </form>
                </nav>

            </div>
        </div>
    </div>


    
    {# <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Content</th>
                <th>CreateAt</th>
                <th>ModifyAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody> #}
    
    <div class="container">
        <div class="row">
        {% for blog in blogs %}
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="..." alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title h5"><a class="link-dark text-decoration-none" href="{{ path('app_blog_show', {'id': blog.id}) }}">{{ blog.title }}</a></h5>
                        {# <p class="card-text">{{ blog.content|slice(0, 200) }}</p> <!-- filters are included with a '|' --> #}
                        <a href="#" class="btn btn-primary">Lire l'article</a>
                        <a href="{{ path('app_blog_edit', {'id': blog.id}) }}" class="btn btn-primary">Editer l'article</a>

                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    <div>
    {% endblock %}
            {# <tr>
                <td>{{ blog.id }}</td>
                <td>{{ blog.title }}</td>
                <td>{{ blog.content }}</td>
                <td>{{ blog.createAt ? blog.createAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ blog.ModifyAt ? blog.ModifyAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_blog_show', {'id': blog.id}) }}">show</a>
                    <a href="{{ path('app_blog_edit', {'id': blog.id}) }}">edit</a>
                </td>
            </tr>

        {% else %} <if there is nothing in the table -->


            <tr>
                <td colspan="6">no records found</td>
            </tr

        {% endfor %}

        </tbody>
    </table>

    <a href="{{ path('app_blog_new') }}">Create new</a>
{% endblock %} #}

Symfony/SUPERBLOG-master/templates/blog/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Blog{% endblock %}

{% block body %}
    <h1>Create new Blog</h1>

    {{ include('blog/_form.html.twig') }}

    <a href="{{ path('app_blog_index') }}">back to list</a>
{% endblock %}

Symfony/SUPERBLOG-master/templates/blog/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blog{% endblock %}

{% block body %}
    <h1 class="text-center my-5">{{ blog.title }}</h1>

    <div class="container">
        <div class="row">
            <div class="col">
                <p class="text-center">{{ blog.content }}</p>
                <p class="ml-4">Billet de blog écrit par <span><i>{{ blog.user.email }}</i> le <i>{{ blog.createAt|date('d-m-Y H:i') }}</i></span></p>
                {% if blog.modifyAt != null %}
                <p class="ml-4">Dernière modification le <span><i>{{ blog.modifyAt|date('d-m-Y H:i') }}</i></span></p>
                {% endif %}

                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-5">
                            <h2>Commentaires</h2>
                                <div id="comment-list">
                                {% for comment in comments %}
                                    <div class="my-3">
                                        <p class="my-0 fw-bold">{{comment.user.email}}<span class="fw-normal"> {{ comment.createAt|date('d-m-Y H:i')  }}</span></p>
                                        <div>{{ comment.content|raw }}</div>
                                    </div>
                                {% endfor %}
                                </div>
                        </div>
                    </div>
                </div>

                <div class="text-center my-4">
                    <h3> Un petit commentaire ?</h3>
                    <textarea id="commentTextarea" cols="100" rows="10"></textarea>
                </div>

                <div class="text-center my-4">
                    <button id="test" class="btn btn-primary">Text AJAX</button>
                </div>


                <div class="text-center">
                    <a  href="{{ path('app_blog_index') }}">Retour à l'index</a>
                </div>
            </div>
        </div>
    </div>



{#    <a href="{{ path('app_blog_edit', {'id': blog.id}) }}">edit</a>#}

{#    {{ include('blog/_delete_form.html.twig') }}#}
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script>
        // NOTRE AJAX
        const test = document.getElementById('test');
        const commentList = document.getElementById('comment-list');


        test.addEventListener('click', function (){

            let textContent = tinymce.get('commentTextarea').getContent();

            fetch("{{ path('app_comment_new') }}", {
                method: "POST",
                headers: {
                    Accept: "application/json",
                },
                body: JSON.stringify({
                    id: {{ blog.id }},
                    content : textContent,
        })
            })
                .then(response => response.json())
                .then(data => {
                    console.log(data);

                    // Ajout d'un commentaire en temps réel
                    createComment(data);

                    // On réinitialise le contenu du textearea apres la réception de la reponse de l'ajax.

                    tinymce.get('commentTextarea').setContent(''); // Avec selecteurs si vous en avez plusieurs
                    // sur la même page.
                    //tinymce.activeEditor.setContent(''); // si il y en a seulement 1
                });
        })


        function createComment(data){
            let user = data.user;
            let content = data.content

            // conversion en date français
            let date = data.date.date
            const dateObj = new Date(date);
            let day = dateObj.getDate() < 10 ? "0" + dateObj.getDate() : dateObj.getDate();
            let month = dateObj.getMonth() < 10 ? "0" + parseInt(dateObj.getMonth() + 1) : parseInt(dateObj.getMonth() + 1);
            let hours = dateObj.getHours() < 10 ? "0" + dateObj.getHours() : dateObj.getHours();
            let minutes = dateObj.getMinutes() < 10 ? "0" + dateObj.getMinutes() : dateObj.getMinutes();
            let convertedDate = ' ' + day + '-' + month + '-'+ dateObj.getFullYear() + ' ' + hours + ":" + minutes;
            let div = document.createElement("div")
            div.innerHTML = `<div class='my-3 '><p class='my-0 fw-bold'>${user}<span class="fw-normal">${convertedDate}</span></p> <div>${content}</div> </div>`;
            commentList.append(div);
        }

    </script>
{% endblock %}